version: "3.11.9"
services:
  app:
    build: .
    volumes:
      - .:/ghs
    ports:
      - "8000:8000"
    image: app:ghs
    container_name: ghs_app
    command: poetry run python manage.py runserver 0.0.0.0:8000
