# Generated by Django 4.2.9 on 2024-05-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_submission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.CharField(max_length=150),
        ),
    ]
