# Generated by Django 4.2.9 on 2024-06-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
